version: "3.8"

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-abc123-this-is-just-for-learning-xyz789
    depends_on:
      - db

volumes:
  postgres_data:
